### ISSUE TITLE
Document installation of native libraries

### ISSUE THREAD

**Issue by jefft** [flajann2/fxruby-enhancement#1]
It would be nice if the README, besides just noting the dependency of the C extension, had some instructions for installing it ("apt-get install ...."). The errors generated by 'gem install fxruby-enhancement' are not that helpful.

**Comment by kholbekj** [comment]
It's supposed to build the c extension when you install the gem. But there seems to be an issue with the fox header, i foxed it (on osx, sorry) with `brew install xquartz; brew install x11/fox; gem install fxruby-enhancement`

**Comment by flajann2** [comment]
Thanks for noting how to proceded with that, knolbekj. Yes, the documentation is incomplete, but I am looking to steadily improve it. I will note the "apt-get install..." as this was an oversight on my behalf.

**Comment by flajann2** [comment]
I have Added reference to the general build setup. And improved the documentation in some other ways as well. Please feel free to raise more issues as they arise, and I will try to address them as quickly as I can.
