### ISSUE TITLE
FXRbApp::openDisplay: unable to open display :0.0

### ISSUE THREAD

**Issue by kholbekj** [flajann2/fxruby-enhancement#2]
Trying to exectute the examples keeps giving me this error, with no further information.. OS X 10.11.6

**Comment by flajann2** [comment]
With OSX, you have to setup and install the Xserver subsystem. I have not had a chance to look into the details of doing this yet. Alas, there is no native port of FOX to the MacOS yet, so you have to treat this like any other X-Windows application you run on OSX.

Sorry for the inconvenience.

**Comment by flajann2** [comment]
I have added more documentation on this issue. Thanks.
